import React from 'react';
import './About.css';

function About() {
    return (
        <>
            <div className="headline-wrapper about underline">
                <h1 className="headline">Hello!</h1>
            </div>
            <div className="about content">
                <p>
                    How does one transcend himself; how does he open himself to new possibility? By realizing the truth of his situation, by dispelling the lie of his character, by breaking his spirit out of its conditioned prison. The enemy, for Kierkegaard as for Freud, is the Oedipus complex. The.child has built up strategies and techniques for keeping his self-esteem in the face of the terror of his situation. These techniques become an armor that hold the person prisoner. The very defenses that he needs in order to move about with self-confidence and self-esteem become his life-long trap. In order totranscend himself he must break down that which he needs in order to live. Like Lear he must throw off all his “cultural lendings” and stand naked in the storm of life. Kierkegaard had no illusions about man's urge to freedom. He knew how comfortable people were inside the prison of their character defenses. Like many prisoners they are comfortable in their limited and protected routines, and the idea of a parole into the wide world of chance, accident, and choice terrifies them. We have only to glance back at Kierkegaards confession in the epigraph to this chapter to see why. In the prison of one's character one can pretend and feel tha the world is manageable, that there a reason for one's life, a ready justification for one’s action. To live automatically and uncritically is to be assured of at least a minimum share of the programmed cultural heroics—what we might call “prison heroism”: the smugness of the insiders who “know.”
                    {/* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas sed enim ut. Tristique nulla aliquet enim tortor at. Ullamcorper a lacus vestibulum sed arcu non. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Arcu non odio euismod lacinia at quis. Felis donec et odio pellentesque diam. A scelerisque purus semper eget. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Tortor aliquam nulla facilisi cras fermentum odio.
                    <br/><br/>Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Pharetra vel turpis nunc eget. Sed vulputate odio ut enim blandit. Odio pellentesque diam volutpat commodo sed egestas egestas. Quis blandit turpis cursus in hac habitasse platea. Nunc sed augue lacus viverra vitae congue eu consequat. Vitae ultricies leo integer malesuada nunc. Vitae ultricies leo integer malesuada nunc vel risus commodo. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Metus vulputate eu scelerisque felis. Id consectetur purus ut faucibus pulvinar elementum integer. Augue eget arcu dictum varius duis at consectetur lorem. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Platea dictumst quisque sagittis purus sit amet. At urna condimentum mattis pellentesque id nibh tortor.
                    <br/><br/>Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Elit eget gravida cum sociis. Quam vulputate dignissim suspendisse in est ante. Diam vulputate ut pharetra sit. Eget felis eget nunc lobortis mattis aliquam. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Et tortor at risus viverra adipiscing at. Amet consectetur adipiscing elit ut. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Sit amet nulla facilisi morbi tempus iaculis urna id.
                    <br/><br/>Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Varius duis at consectetur lorem donec massa sapien faucibus et. Tempus imperdiet nulla malesuada pellentesque. Faucibus ornare suspendisse sed nisi lacus sed. Sem et tortor consequat id porta nibh. Lacus vel facilisis volutpat est velit egestas dui id. Interdum velit euismod in pellentesque massa placerat duis ultricies. Purus viverra accumsan in nisl nisi. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Eu turpis egestas pretium aenean pharetra. Id eu nisl nunc mi ipsum faucibus vitae aliquet. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Eget dolor morbi non arcu risus quis varius quam. Consequat nisl vel pretium lectus quam id leo in vitae. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Mi bibendum neque egestas congue quisque.
                    <br/><br/>Vivamus at augue eget arcu dictum varius duis at. Libero id faucibus nisl tincidunt eget. At in tellus integer feugiat scelerisque varius. Justo nec ultrices dui sapien eget mi proin sed libero. Adipiscing elit ut aliquam purus. Ultricies mi quis hendrerit dolor magna eget est lorem ipsum. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Posuere sollicitudin aliquam ultrices sagittis. Turpis massa sed elementum tempus egestas sed sed. Diam ut venenatis tellus in. Ultrices sagittis orci a scelerisque purus semper eget. Odio ut sem nulla pharetra diam sit. */}
                </p>
            </div>
        </>
    );
}

export default About;
